version: 1
disable_existing_loggers: True
formatters:
    simple:
        format: "%(asctime)s - [%(filename)s][%(funcName)s] - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: ./logs/rstintegration.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        encoding: utf8

loggers:
    Common:
        level: INFO
        handlers: [ console, file_handler ]
        propagate: no
    RVisionSOARIntegration:
        level: INFO
        handlers: [ console, file_handler ]
        propagate: no
root:
    level: INFO
    handlers: [console, file_handler]